name: nextcloud-with-tailscale

networks:
  nextcloud-net:
    driver: bridge

services:
  nextcloud-ts:
    image: tailscale/tailscale:latest
    container_name: nextcloud-ts
    hostname: nextcloud-ts
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_USERSPACE=false
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./config/tailscale/serve-config.json:/config/serve-config.json
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    networks:
      - nextcloud-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
  postgres:
    image: postgres:16-alpine
    container_name: nextcloud-postgres
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    networks:
      - nextcloud-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - nextcloud-config:/config
      - nextcloud-storage:/data
    ports:
      - 443:443
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  nextcloud-config:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nextcloud/nextcloud-config
      o: bind
  nextcloud-storage:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nextcloud/nextcloud-storage
      o: bind
  nextcloud-db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nextcloud/nextcloud-db
      o: bind
  tailscale-state:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nextcloud/tailscale-state
      o: bind